- name: Get rustup
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/rustup-init
    mode: "u=rx,g=rx,o=rx"

- name: Run rustup-init
  command: /tmp/rustup-init -y

- name: Install stable
  command: rustup install stable
  environment:
    PATH: "{{ansible_env.HOME}}/.cargo/bin:{{ ansible_env.PATH }}"

- name: Set rust stable as default
  command: rustup default stable
  environment:
    PATH: "{{ansible_env.HOME}}/.cargo/bin:{{ ansible_env.PATH }}"
