#!/usr/bin/env bash

sudo apt-get install build-essential \
	libssl-dev \
	python-apt \
	python-apt-common \
	python2.7-dev \
	python-pip \
	python-setuptools \
	python-distutils-extra \
	python-virtualenv \
	-y

if [ ! -d .env ]; then
	python -m virtualenv --python=`which python2` --system-site-packages .env
fi

source .env/bin/activate
python -m pip install -U pip
python -m pip install -r requirements.txt

ansible-playbook -K "$@"
