#!/usr/bin/env bash

python -m ensurepip --user
python -m pip install --user --upgrade virtualenv

python -m virtualenv --python=`which python2` .env &&
    source .env/bin/activate &&
    python -m pip install -U pip &&
    python -m pip install ansible

ansible-playbook -K macos.yml


