- name: Pull down Alacritty source
  git:
    repo: "https://github.com/jwilm/alacritty.git"
    dest: /tmp/alacritty
    clone: yes

- name: Build the cargo deb
  command: cargo install cargo-deb
  args:
    chdir: /tmp/alacritty

- name: Install the deb
  command: cargo deb --install
  become: yes
