tasks:
  - include: package_install.yml
  - include: emacs_install.yml
  - include: go_install.yml
  - include: dot_files.yml
  - include: gnome_setup.yml

# - name: Git setup
#   copy: src=.gitconfig dest=/home/nerraw/

# - name: GHC config
#   copy: src=.ghc dest=/home/nerraw/
  

# - name: Make .emacs directory
#   command: mkdir -p /home/nerraw/.emacs.d/

# - name: Copy .emacs files
#   copy: src="{{ item }}" dest=/home/nerraw/.emacs.d/
#   with_items:
#     - init.el
#     - lisp

# - name: Make Terminator config directory
#   command: mkdir -p /home/nerraw/.config/terminator/

# - name: Copy Terminator config
#   copy: src=config dest=/home/nerraw/.config/terminator/
