---
macos_defaults:
  # Hide the top menu bar
  - domain: NSGlobalDomain
    key: _HIHideMenuBar
    value: true
    type: bool

  # Remove magnification from the dock
  - domain: com.apple.dock
    key: magnification
    value: false
    type: bool

  # Set the icon size for things on the dock
  - domain: com.apple.dock
    key: tilesize
    value: 36
    type: float

  # Move the dock to the left
  - domain: com.apple.dock
    key: orientation
    value: left
    type: string

  # Remove autohide-delay from the dock
  - domain: com.apple.dock
    key: autohide-delay
    value: 0
    type: float

  # Remove the hide/show animation from the dock
  - domain: com.apple.dock
    key: autohide-time-modifier
    value: 0
    type: float

    # Automatically hide and show the Dock
  - domain: com.apple.dock
    key: autohide
    value: true
    type: bool

    # Set the amount of time between key repeats to super fast
  - domain: NSGlobalDomain
    key: KeyRepeat
    value: 1
    type: int

    # Set low key press duration before repeating a key
  - domain: NSGlobalDomain
    key: InitialKeyRepeat
    value: 10
    type: int

  # Enable tap to click
  - domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: Clicking
    value: true
    type: bool

  - domain: NSGlobalDomain
    key: com.apple.mouse.tapBehavior
    value: 1
    type: int
  
  - domain: "com.apple.controlstrip"
    key: "FullCustomized"
    value:
      - "com.apple.system.group.brightness"
      - "com.apple.system.mission-control"
      - "com.apple.system.launchpad"
      - "com.apple.system.group.keyboard-brightness"
      - "com.apple.system.group.media"
      - "com.apple.system.group.volume"
      - "com.apple.system.screen-lock"
    type: array

  - domain: "com.apple.controlstrip"
    key: "MiniCustomized"
    value:
      - "com.apple.system.brightness"
      - "com.apple.system.volume"
      - "com.apple.system.mute"
      - "com.apple.system.notification-center"
    type: array
