- name: Add gnome specific ppas
  apt_repository: repo={{ item }} update-cache=yes
  with_items: "{{gnome_ppa_repos}}"
  become: yes
  
- name: Install necessary gnome_packages
  apt: pkg="{{ item }}" state=latest
  with_items: "{{gnome_packages}}"
  become: yes

- name: Install the gnome extensions
  include: extensions.yml gnome_extension_id="{{ item }}"
  with_items: "{{ gnome_extension_ids }}"
