- name: Emacs build-deps
  apt:
    name: emacs24
    state: build-dep
  sudo: yes

- name: Get Emacs
  get_url:
    url: http://ftp.gnu.org/gnu/emacs/emacs-24.5.tar.gz
    dest: /tmp/emacs.tar.gz

- name: Untar emacs
  unarchive:
    copy: no
    dest: /tmp/
    src: /tmp/emacs.tar.gz

- name: Configure emacs build
  command: ./configure
  args:
    chdir: /tmp/emacs-24.5

- name: Make emacs
  command: make
  args:
    chdir: /tmp/emacs-24.5

- name: Install emacs
  command: make install
  args:
    chdir: /tmp/emacs-24.5
  sudo: yes

- name: Add Emacs to applications
  copy:
    src: Emacs-24.desktop
    dest: /usr/share/applications/
  sudo: yes

- include: fonts.yml
  
