- name: Get Go tar
  get_url: url=https://storage.googleapis.com/golang/go{{ go_version }}.linux-amd64.tar.gz dest=/tmp

- name: Install GO
  command: tar -C /usr/local -xzf /tmp/go{{ go_version }}.linux-amd64.tar.gz
  sudo: yes
  
- name: Add GOPATHS
  lineinfile:
    dest="{{ item.file }}"
    insertafter=EOF
    line="{{ item.line }}"
  with_items:
    - { file: '/etc/profile', line: 'export PATH=$PATH:/usr/local/go/bin' }
    - { file: '~/.bashrc', line: 'export PATH=$PATH:$HOME/go' }
    - { file: '~/.bashrc', line: 'export GOPATH=$HOME/go'}
  sudo: yes


- name: Create GOPATH
  file:
    path: "{{go_path}}"
    state: directory
    
- name: Install go packages
  command: /usr/local/go/bin/go get {{item}}
  environment:
    GOPATH: "{{go_path}}"
  with_items: go_packages
