ppa_repositories:
  - ppa:hvr/ghc
  
packages:
  - firefox
  - openssh-server
  - terminator
  - python-pip
  - alien
  - dpkg-dev
  - debhelper
  - build-essential
  - libreoffice
  - git
  - git-core
  - meld
  - nginx
  - smbclient
  - curl
  - libcurl3
  - wget
#  - flashplugin-installer
  - software-properties-common
  - cabal-install-1.20
  - xmonad
  - dmenu
  - ghc-7.8.4
  - happy-1.19.5
  - alex-3.1.4
  - stow
