ppa_repositories:
  - ppa:hvr/ghc
  
packages:
  - openssh-server
  - python3
  - python-pip
  - alien
  - dpkg-dev
  - debhelper
  - build-essential
  - git
  - mercurial
  - git-core
  - meld
  - nginx
  - smbclient
  - curl
  - libcurl3
  - wget
  - software-properties-common
  - cabal-install-1.20
  - ghc-7.8.4
  - happy-1.19.5
  - alex-3.1.4
  - stow
  