ppa_repositories:
  - ppa:satyajit-happy/themes
  - ppa:numix/ppa
  - ppa:hvr/ghc
  
packages:
  - firefox
  - openssh-server
  - terminator
  - python-pip
  - alien
  - dpkg-dev
  - debhelper
  - build-essential
  - libreoffice
  - git
  - git-core
  - meld
  - nginx
  - smbclient
  - curl
  - libcurl3
  - wget
  - flashplugin-installer
  - software-properties-common
  - cabal-install-1.20
  - xmonad
  - dmenu
  - ghc-7.8.4
  - happy-1.19.5
  - alex-3.1.4
  - gnome-tweak-tool
  - shimmer-themes
  - shimmer-wallpapers
  - numix-gtk-theme
  - numix-icon-theme
  - numix-icon-theme-circle
  - numix-wallpaper-mr-numix
  - gnome-shell-extensions
  - gnome-shell-theme-elegance-colors

go_packages:
  - golang.org/x/tools/cmd/goimports
  - golang.org/x/tool/cmd/oracle
  - github.com/nsf/gocode

go_path: "{{ansible_env.Home}}/go"

