- name: Install docker dependencies
  apt:
    package: "{{ item }}"
    state: present
    update_cache: true
  become: yes
  with_items: "{{ docker_deps }}"


- name: Fetch docker's apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  become: yes

- name: Add docker's apt repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    update_cache: true
  become: yes

- name: Install docker
  apt:
    package: docker-ce
  become: yes

- name: Add docker group
  group:
    name: docker
  become: yes
  
- name: Add the current user to the docker group
  user:
    name: "{{ ansible_env.USERNAME }}"
    append: yes
    groups: docker
  become: yes
  
- name: Start docker on boot
  systemd:
    name: docker
    enabled: yes
  become: yes
    
